spring.application.name=llm_bedrock_test
llm.mode=lending
tools.mode=lambda
#  local

aws.region=eu-central-1
bedrock.region=eu-central-1
bedrock.modelId=anthropic.claude-3-haiku-20240307-v1:0

bedrockInference.maxTokens=256
bedrockInference.temperature=0.2
bedrockInference.topP=0.9